src/Entity/Utilisateur.php
<?php

namespace App\Entity;

use App\Repository\UtilisateurRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UtilisateurRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class Utilisateur implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 100)]
    private ?string $Nom = null;

    #[ORM\Column(length: 100)]
    private ?string $Prenom = null;

    #[ORM\OneToMany(mappedBy: 'Utilisateur', targetEntity: Panier::class)]
    private Collection $paniers;

    public function __construct()
    {
        $this->paniers = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    /**
     * @return Collection<int, Panier>
     */
    public function getPaniers(): Collection
    {
        return $this->paniers;
    }

    public function addPanier(Panier $panier): self
    {
        if (!$this->paniers->contains($panier)) {
            $this->paniers->add($panier);
            $panier->setUtilisateur($this);
        }

        return $this;
    }

    public function removePanier(Panier $panier): self
    {
        if ($this->paniers->removeElement($panier)) {
            // set the owning side to null (unless already changed)
            if ($panier->getUtilisateur() === $this) {
                $panier->setUtilisateur(null);
            }
        }

        return $this;
    }

    public function __toString(): string
    {
        return $this->getNom() . ' ' . $this->getPrenom();
    }

}

src/Form/UtilisateurType.php
<?php

namespace App\Form;

use App\Entity\Utilisateur;
use Doctrine\DBAL\Types\StringType;
use Doctrine\DBAL\Types\TextType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;

class UtilisateurType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Nom',null,[
                "label" => "Last Name",
                'constraints' => [
                    new NotBlank([
                        'message' => 'Please enter a name',
                    ]),
                    new Length([
                        'min' => 2,
                        'minMessage' => 'Your name should be at least 3 characters',
                        // max length allowed by Symfony for security reasons
                        'max' => 4096,
                    ]),
                ]
            ])
            ->add('Prenom',
                null,
                [
                    "label" => "First Name",
                    'constraints' => [
                        new NotBlank([
                            'message' => 'Please enter a first name',
                        ]),
                        new Length([
                            'min' => 2,
                            'minMessage' => 'Your description should be at least 3 characters',
                            // max length allowed by Symfony for security reasons
                            'max' => 4096,
                        ]),
                    ]
                ]
            )
            
            ->add('email',EmailType::class,[
                "label" => "Email",
                'constraints' => [
                    new NotBlank([
                        'message' => 'Please enter a email',
                    ]),
                    new Length([
                        'min' => 2,
                        'minMessage' => 'Your email should be at least 3 characters',
                        // max length allowed by Symfony for security reasons
                        'max' => 4096,
                    ]),
                ]
            ])
            ->add('password', PasswordType::class, [
                // instead of being set onto the object directly,
                // this is read and encoded in the controller
                'mapped' => false,
                'attr' => ['autocomplete' => 'new-password'],
                'constraints' => [
                    new NotBlank([
                        'message' => 'Please enter a password',
                    ]),
                    new Length([
                        'min' => 6,
                        'minMessage' => 'Your password should be at least {{ limit }} characters',
                        // max length allowed by Symfony for security reasons
                        'max' => 4096,
                    ]),
                ],
            ])
            ->add('Save',SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Utilisateur::class,
        ]);
    }
}

src/Controller/UtilisateurController.php
<?php

namespace App\Controller;

use App\Entity\Utilisateur;
use App\Form\UtilisateurType;
use App\Form\UtilisateurUpdateType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\Translation\TranslatorInterface;

class UtilisateurController extends AbstractController
{
    #[Route('/utilisateur', name: 'app_utilisateur')]
    public function index(EntityManagerInterface $em,Request $request,TranslatorInterface $trans): Response
    {
        $user = $this->getUser();
        $users = [];
        $users_inscrit = [];
        if($user == null)
            return $this->redirectToRoute('app_login');
        
        if( $user->getRoles()[0] == "ROLE_SUPER_ADMIN"){
            $tmps = $em->getRepository(Utilisateur::class)->findAll();
            foreach($tmps as $utilisateur){
                if($utilisateur->getPaniers()[$utilisateur->getPaniers()->count()-1]->isEtat() == false){
                    array_push($users,[$utilisateur,$utilisateur->getPaniers()[$utilisateur->getPaniers()->count()-1]->getId()]);
                }
                
            }

            //user  avec un panier non validé
            $users = array_values($users);
            
            //uuser inscrit sur la platform
            $users_inscrit = $em->getRepository(Utilisateur::class)->findAll();

            usort($users_inscrit, function($a, $b) {
                return $a->getId() <=> $b->getId();
            });
        }

        $historique = $user->getPaniers();
        $lstContenuePanier = [];
        foreach($historique as $contenue){
            array_push($lstContenuePanier,$contenue->getContentPaniers());
        }

        $form = $this->createForm(UtilisateurUpdateType::class,$user);
        $form->handleRequest($request); 
        if($form->isSubmitted() && $form->isValid()){
            $em->persist($user); 
            $em->flush(); 
            $this->addFlash('success',$trans->trans('flash.success.UpdateProduct'));
        }

        return $this->render('utilisateur/index.html.twig', [
            "form" => $form->createView(),
            "user" => $user,
            "historique" => $historique,
            "contenuePanier" => $lstContenuePanier,
            "users" => $users,
            "users_inscrit" => $users_inscrit,
        ]);
    }

    
}

templates/utilisateur/index.html.twig
{% extends 'base.html.twig' %}


{% block body %}


<div class="container border">
    <h1 class="text-center">Profil</h1>
    <p>{{'Last Name'|trans}} : {{ user.nom }}</p>
    <p>{{'First Name'|trans}} : {{ user.prenom }}</p>
    <p>{{'Email'|trans}} : {{ user.email }}</p>
    <div class="text-center">
        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#exampleModal">
            <a class="nav-link" href="{{path('app_logout')}}">Déconnexion</a>
        </button>
    </div
</div>

<div class="container ">
    {{ form_start(form) }}
    <p>{{'Last Name'|trans}}  : {{ form_widget(form.Nom,{ 'value': user.nom}) }} <p/>
    <p>{{'First Name'|trans}} : {{ form_widget(form.Prenom,{ 'value': user.prenom}) }} </p>
    <p>{{'Email'|trans}} :      {{ form_widget(form.email,{ 'value': user.email}) }} </p>
    <p>{{ form_widget(form.Update) }} </p>
    {{ form_end(form) }}
</div>


{% for types,messages in app.flashes %}
    <div class="alert alert-{{types}}">
        {% for message in messages %}
            <p>{{message}}</p>
        {% endfor %}
    </div>
{% endfor %}

<hr></hr>

{% if is_granted('ROLE_SUPER_ADMIN') %}
    <div>
        <h1>{{'User.List of cart'|trans}}</h1>
        {% for utilisateur in users %}
            <div class="container">
                <p> {{ utilisateur[0].email }} </p>
                <p> id panier: {{ utilisateur[1]}} </p>
                <a href="{{ path('app_panier_historique', {'id': utilisateur[1]}) }}">voir le panier</a>
            </div>
        {% endfor %}
    </div>

    <div>
        <h2> {{'User.List of user'|trans}}</h2>
        {% for user in users_inscrit %}
            <div class="container">
                <p> {{ user.email }} </p>
                <p> {{ user.nom }} </p>
                <p> {{ user.prenom }} </p>
            </div>
        {% endfor %}
    </div>
{% endif %}
<div >
    {% for panier in historique %}
        {% if panier.Etat == 1 %}     
        <div class="card mb-3">
            <div class="card-header">
                Commande du {{ panier.DateAchat|date('d/m/Y') }} n°{{ panier.id }}
            </div>
            <div class="card-body pb-3">
                {% set total = 0 %}
                {% for x in contenuePanier %}
                    {% for contenue in x %}
                        {% if contenue.panier.id == panier.id %}
                            {% for product in contenue.Produit %}
                                {% set total = total + contenue.Quantite * product.Prix %}
                            {% endfor %}
                        {% endif %}
                    {% endfor %}
                {% endfor %}
                <h5 class="card-title">total de la commande :  {{ total }} $</h5>
                <a href="{{ path('app_panier_historique', {'id': panier.id}) }}" class="btn btn-primary">voir le panier</a>
            </div>
        </div>

        <div class="container">
                
        </div>
        {% endif %}
    {% endfor %}
</div> 

{% endblock %}